### ISSUE TITLE
metasploit-credential not in the bundle,

### ISSUE THREAD

**Issue by handsomebeast** [rapid7/metasploit-credential#133]
How to solve this

**Comment by handsomebeast** [comment]
$ msfconsole
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
        36: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `<main>'
        35: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `require'
        34: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        33: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        32: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        31: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        30: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
        29: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        28: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
        27: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
        26: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
        25: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:61:in `<class:Framework>'
        24: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        23: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
        22: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:23:in `<top (required)>'
        21: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:61:in `<class:DBManager>'
        20: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
        19: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
        18: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit-credential-2.0.14/lib/metasploit/credential.rb:11:in `<top (required)>'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit_data_models-2.0.17/lib/metasploit_data_models.rb:15:in `<top (required)>'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record.rb:32:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record.rb:130:in `<module:ActiveRecord>'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:3:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
         1: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so (LoadError)
        19: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `<main>'
        18: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `require'
        17: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        16: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        15: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        14: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        13: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
        10: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
         9: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
         8: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:61:in `<class:Framework>'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
         5: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:23:in `<top (required)>'
         4: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:61:in `<class:DBManager>'
         3: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
         2: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
         1: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:20:in `optionally'
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:25:in `rescue in optionally': undefined method `without' for #<Bundler::Settings:0xf4a58ae0> (NoMethodError)
$

**Comment by houcemlaw** [comment]
Same error here!
Are the community experiencing such an issue ?
At first glance it seems like this related to a new gem/ruby update. The library is installed but not reachable though.
Guys! Any clue would be more than welcome.
Thx a lot

**Comment by handsomebeast** [comment]
Let's see m facing this prblm from 3 days

**Comment by bcoles** [comment]
It looks like you're using Termux.

Termux is not officially supported. https://github.com/rapid7/metasploit-framework/issues/11023

It appears this issue may been patched. Refer to https://github.com/rapid7/metasploit-framework/issues/11495#issuecomment-468007703

**Comment by handsomebeast** [comment]
Not working how to fix?

**Comment by bcoles** [comment]
https://github.com/rapid7/metasploit-framework/issues/11495#issuecomment-468007703 :

> there seems to be a fix https://github.com/termux/termux-packages/issues/715#issuecomment-468003094 please give it a try, and if it doesn't work report on https://github.com/termux/termux-packages/issues/715

**Comment by houcemlaw** [comment]
Indeed! i am using termux.
thanks a lot that was the right answer and it worked.
So to make it short this is what you'll need:

wget https://github.com/termux/termux-packages/files/2912002/fix-ruby-bigdecimal.sh.txt 

bash fix-ruby-bigdecimal.sh.txt

**Comment by handsomebeast** [comment]
I have tried not working

**Comment by bcoles** [comment]
https://github.com/termux/termux-packages/issues/715

**Comment by handsomebeast** [comment]
Plz help still not working this method plz help m arm device

**Comment by bcoles** [comment]
https://github.com/termux/termux-packages/issues/715

**Comment by handsomebeast** [comment]
Not working help me to fix this

**Comment by bcoles** [comment]
https://github.com/rapid7/metasploit-framework/issues/11495#issuecomment-468007703

> there seems to be a fix https://github.com/termux/termux-packages/issues/715#issuecomment-468003094 please give it a try, and if it doesn't work report on https://github.com/termux/termux-packages/issues/715

The Termux team have asked you to report your issues here:

https://github.com/termux/termux-packages/issues/715

**Comment by handsomebeast** [comment]
I I am using arm device so that command not working for me

**Comment by picassotech** [comment]
This works
wget https://github.com/termux/termux-packages/files/2912002/fix-ruby-bigdecimal.sh.txt

bash fix-ruby-bigdecimal.sh.txt

**Comment by mayday12138** [comment]
> Indeed! i am using termux.
> thanks a lot that was the right answer and it worked.
> So to make it short this is what you'll need:
> 
> wget https://github.com/termux/termux-packages/files/2912002/fix-ruby-bigdecimal.sh.txt
> 
> bash fix-ruby-bigdecimal.sh.txt

thanks,i am fixed

**Comment by DIW25** [comment]
Indeed! i am using termux.
thanks a lot that was the right answer and it worked.
So to make it short this is what you'll need:

wget https://github.com/termux/termux-packages/files/2912002/fix-ruby-bigdecimal.sh.txt

bash fix-ruby-bigdecimal.sh.txt

This doesn't work for me . 
Can someone suggest me with another solution

**Comment by FSF-ALL-STAR** [comment]
This works, in my solution from status 
Thanks bradah

wget https://github.com/termux/termux-packages/files/2912002/fix-ruby-bigdecimal.sh.txt

bash fix-ruby-bigdecimal.sh.txt

**Comment by Hackermes** [comment]
Guys I have facing the problem very long time
Can you help me.......
... Traceback (most recent call last):
        2: from /data/data/com.termux/files/usr/bin/lolcat:25:in `<main>'
        1: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem lolcat (>= 0.a) with executable lolcat (Gem::GemNotFoundException)
Traceback (most recent call last):
        2: from /data/data/com.termux/files/usr/bin/lolcat:25:in `<main>'
        1: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem lolcat (>= 0.a) with executable lolcat (Gem::GemNotFoundException)
