### ISSUE TITLE
KeyError in creation.rb

### ISSUE THREAD

**Issue by imander** [rapid7/metasploit-credential#141]
When running the crack_windows auxiliary module in metasploit a key error is thrown.  The :address option should be set with a default option to avoid this error condition.

  
![image](https://user-images.githubusercontent.com/16767909/72212613-057b6b00-3494-11ea-83a3-ac6df46716b9.png)

**Comment by h00die** [comment]
Pretty sure I know the issue, (@jmartin-r7), can you post your `show options` and a few sanitized lines before the screenshot? Was a hash cracked?

**Comment by imander** [comment]
The error occurred when I was using a custom word list.  When the custom word list was exhausted the module went on to crack with the default word list.  There was one password cracked with the custom word list (which was expected) but the default word list never ran.  If it had more passwords would have been cracked.  I opened https://github.com/rapid7/metasploit-credential/pull/142 which has additional details and screenshots.

**Comment by imander** [comment]
It looks like I am not the only person who has experienced this.  [This write-up](https://null-byte.wonderhowto.com/how-to/use-john-ripper-metasploit-quickly-crack-windows-hashes-0200322/) explaining how to crack windows hashes has a screenshot showing the same stack trace.

**Comment by h00die** [comment]
Thanks for all the extra input!

**Comment by imander** [comment]
Just tested against the most recent version (`metasploit-credential-3.0.4`) and this issue appears to be fixed
