### ISSUE TITLE
metasploit-credential 

### ISSUE THREAD

**Issue by marioskan** [rapid7/metasploit-credential#144]
I just opened kali, I've been using msfconsole without issues the last days but know I can't open the console.

> Executing “sudo msfdb init && msfconsole”
[i] Database already started
[i] The database appears to be already configured, skipping initialization
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
    	13: from /usr/bin/msfconsole:48:in `<main>'
    	12: from /usr/bin/msfconsole:48:in `require'
    	11: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
    	10: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
     	9: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
     	8: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
     	7: from /usr/share/metasploit-framework/lib/msf/core.rb:44:in `<top (required)>'
     	6: from /usr/share/metasploit-framework/lib/msf/core.rb:44:in `require'
     	5: from /usr/share/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
     	4: from /usr/share/metasploit-framework/lib/msf/core/db_manager.rb:66:in `<class:DBManager>'
     	3: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
     	2: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
     	1: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:20:in `optionally'
/usr/share/metasploit-framework/lib/metasploit/framework/require.rb:25:in `rescue in optionally': undefined method `without' for #<Bundler::Settings:0x0000561d16167608> (NoMethodError)
Did you mean?  with_options

**Comment by adfoster-r7** [comment]
Wasn't able to replicate, closing for now
